### ISSUE TITLE
Markdown not processed

### ISSUE THREAD

**Issue by codeaddslife** [lightbend/cloudflow#16]
**Describe the bug**
In the documentation some links/images are not processed correctly. 

**To Reproduce**
Go to https://cloudflow.io/docs/current/get-started/hello-world-example.html
The link to 'avro schema' and the image pipe.001.jpeg are not displayed. 

**Expected behavior**
To be processed correctly

**Screenshots**
-

**Additional context**
-

**Comment by agemooij** [comment]
This has been fixed as part of the ongoing process to open source the docs ASAP. 
We're almost there but in the mean time we have republished the docs and these specific issues have been addressed.

**Comment by codeaddslife** [comment]
I'm still seeing the problem. Or do you mean that this will come online later? Thanks anyways already for looking into this!
